/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as CheckoutSuccessLegacyRouteImport } from './routes/checkout-success-legacy'
import { Route as CheckoutErrorLegacyRouteImport } from './routes/checkout-error-legacy'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutErrorRouteImport } from './routes/checkout.error'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessLegacyRoute = CheckoutSuccessLegacyRouteImport.update({
  id: '/checkout-success-legacy',
  path: '/checkout-success-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutErrorLegacyRoute = CheckoutErrorLegacyRouteImport.update({
  id: '/checkout-error-legacy',
  path: '/checkout-error-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutErrorRoute = CheckoutErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/checkout-error-legacy': typeof CheckoutErrorLegacyRoute
  '/checkout-success-legacy': typeof CheckoutSuccessLegacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout-error-legacy': typeof CheckoutErrorLegacyRoute
  '/checkout-success-legacy': typeof CheckoutSuccessLegacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/checkout-error-legacy': typeof CheckoutErrorLegacyRoute
  '/checkout-success-legacy': typeof CheckoutSuccessLegacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout/error': typeof CheckoutErrorRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/checkout-error-legacy'
    | '/checkout-success-legacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/checkout/error'
    | '/checkout/success'
    | '/products/$productId'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout-error-legacy'
    | '/checkout-success-legacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/checkout/error'
    | '/checkout/success'
    | '/products/$productId'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/checkout-error-legacy'
    | '/checkout-success-legacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/checkout/error'
    | '/checkout/success'
    | '/products/$productId'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CheckoutErrorLegacyRoute: typeof CheckoutErrorLegacyRoute
  CheckoutSuccessLegacyRoute: typeof CheckoutSuccessLegacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success-legacy': {
      id: '/checkout-success-legacy'
      path: '/checkout-success-legacy'
      fullPath: '/checkout-success-legacy'
      preLoaderRoute: typeof CheckoutSuccessLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-error-legacy': {
      id: '/checkout-error-legacy'
      path: '/checkout-error-legacy'
      fullPath: '/checkout-error-legacy'
      preLoaderRoute: typeof CheckoutErrorLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/error': {
      id: '/checkout/error'
      path: '/error'
      fullPath: '/checkout/error'
      preLoaderRoute: typeof CheckoutErrorRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutErrorRoute: typeof CheckoutErrorRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutErrorRoute: CheckoutErrorRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CheckoutErrorLegacyRoute: CheckoutErrorLegacyRoute,
  CheckoutSuccessLegacyRoute: CheckoutSuccessLegacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
